"""Langfuse tracing (Langfuse Python SDK v4, OpenTelemetry-based) — down to every step.

1 trace = 1 /invocations request. Standard observation tree (fixed names for filters/dashboards):

  agent.invoke  [agent]   input=message · output=answer · user_id · session_id · tags · version
  ├─ auth                  [event]  output={user_id, mode, iss, aud, exp}   (token is NOT logged)
  ├─ tools.collect         [span]   output={local, memory, mcp:{server:[tools]}, mcp_errors}
  │   └─ mcp.list_tools    [span]   input={server, transport, auth, cached} · output=[tool names]
  └─ agent.graph           [chain]  (LangGraph — auto-generated by CallbackHandler, input/output = state)
      ├─ compress          [chain]
      │   └─ context.compress [span] metadata={tokens_before, threshold, decision, removed}
      │       └─ context.summarize [chain] → <model> [generation] model · usage · cost
      ├─ recall            [chain]
      │   └─ memory.recall [span]  input={query, namespace, limit} · output={facts, count, latency}
      ├─ agent             [chain]
      │   ├─ context.hard_trim [event, WARNING] when a hard cut is needed
      │   └─ llm.<task>    [chain]  metadata={llm_task, llm_tier} · linked to the Langfuse prompt version
      │       │                     (Prompt Management) — app/llm get_llm() names this chain
      │       └─ <model>   [generation] NAME = model (e.g. qwen/qwen3.8-flash) · input=messages+tool schemas ·
      │                    output · model_parameters · usage{input, output, input_cache_read,
      │                    cache_creation_*, output_reasoning} · cost · TTFT (completion_start_time)
      │                    (+ a second <model> generation when the primary fails and a fallback answers)
      ├─ tools             [chain]
      │   └─ <tool>        [tool]   input=args · output=result · level=ERROR on failure
      │       └─ memory.save [span] (when tool = remember)
      └─ agent ... (loop)
  score user_feedback (-1|0|1) attached to trace_id when the frontend sends feedback (1 score per user+trace:
  a new tap overwrites the previous one — deterministic score id).

Env (read by the SDK): LANGFUSE_PUBLIC_KEY, LANGFUSE_SECRET_KEY, LANGFUSE_BASE_URL (or LANGFUSE_HOST),
LANGFUSE_SAMPLE_RATE, LANGFUSE_TRACING_ENABLED, LANGFUSE_DEBUG. Missing keys => every function is a no-op.

Masking: `mask=_mask` covers input/output/metadata; `status_message` is NOT passed through `mask` by the SDK ⇒
the helpers here mask it themselves and `mask_otel_spans=_mask_otel_spans` re-masks it on every exported span
(CallbackHandler errors included). Exceptions never propagate through an OTel span context manager (that would
export the raw message as an `exception` event + span status).
"""

from __future__ import annotations

import contextlib
import dataclasses
import functools
import hashlib
import inspect
import logging
import re
import time
from collections.abc import Iterator
from typing import Any

from pydantic import BaseModel

from app.config import Settings

log = logging.getLogger(__name__)

_client: Any = None
# Secret KEYS: the key name (camelCase → snake, lower, "-"/" " → "_") is split on "_"; it is secret if a part is
# one of _SECRET_PARTS or it contains one of _SECRET_SUBSTRINGS. Matches x_api_key, refresh_token, id_token,
# set_cookie, tavilyApiKey, langfuse_secret_key, pin_code, x_amz_signature… but NOT max_tokens / prompt_tokens /
# input_token_details (usage), spinner, pinned, tokenizer (a part must be EXACTLY the secret word).
_SECRET_PARTS = {
    "authorization",
    "token",
    "secret",
    "password",
    "passwd",
    "pwd",
    "passphrase",
    "cookie",
    "credential",
    "credentials",
    "otp",
    "cvv",
    "cvc",
    "signature",
    "sig",
}
_SECRET_SUBSTRINGS = ("api_key", "apikey", "private_key", "secret_key", "access_key")
# "pin" is also Vietnamese for battery ("Dung lượng pin: 5000mAh") ⇒ a `pin` key is secret only when its value
# looks like a PIN code (4–8 digits); product specs stay readable.
_PIN_PARTS = {"pin", "pincode"}
_PIN_VALUE_RE = re.compile(r"^\s*\d{4,8}\s*$")
# token_usage, credential_type, token_use, input_token_details… describe a secret, they are not one
_NOT_SECRET_LAST_PARTS = {
    "usage",
    "type",
    "use",
    "count",
    "limit",
    "expires",
    "expiry",
    "ttl",
    "details",
}
# Credential after Bearer/Basic: ≥ 8 chars with a digit/token symbol or a lower→UPPER switch inside the word
# (base64 like "dXNlcjpw…") — so prose like "basic idea", "Basic plan", "Basic Information" is left alone.
_BEARER_RE = re.compile(  # case-insensitive keyword only: the lower→UPPER check below must stay case-sensitive
    r"\b((?i:bearer|basic))(\s+)(?=[A-Za-z0-9._~+/-]*(?:[0-9+/=._~-]|[a-z][A-Z]))[A-Za-z0-9\-._~+/]{8,}=*"
)
_JWT_RE = re.compile(r"eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}")
_API_KEY_RE = re.compile(r"\b(?:sk|vn|rk)-[A-Za-z0-9_-]{20,}")  # OpenAI-style / GreenNode MaaS keys
_URL_CRED_RE = re.compile(r"(?<=://)([^/\s:@]+):([^/\s@]+)@")  # scheme://user:password@host
# key=value / key: value / "key": "value" INSIDE TEXT (URL query, header dump, JSON or repr in a string, log
# line). Only the key+separator is matched here; the key is then checked with _is_secret_key and only a secret
# key's value is consumed — so `url=https://x/?access_token=…` still reaches the access_token pair.
_KV_KEY_RE = re.compile(r"""(?<![\w-])(\\?["']?)([A-Za-z][A-Za-z0-9_-]{0,63})\1[ \t]*[:=][ \t]*""")
_KV_VALUE_RE = re.compile(
    r"""\\"(?:[^"\\\n]|\\[^"\n])*\\"|"(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*'"""  # \"…\" (JSON in JSON) "…" '…'
    r"""|((?i:bearer|basic|token|digest)[ \t]+)?[^\s"'&,;<>()\[\]{}\\]+"""  # unquoted, optional auth scheme
)
# Default PII (TRACE_MASK_PII): email, VN mobile (+84/0 then 3/5/7/8/9 + 8 digits — "0.123456789" is a number),
# card numbers (Luhn), CCCD-shaped 12 digits (0 + province 00–96 + century/gender 0–3 + 8 digits; other 12-digit
# codes such as order ids stay readable), and ANY 9/12-digit number after an ID keyword (CMND/CCCD/căn cước…
# up to 30 chars before the number, "ID" up to 12). Extend per project.
# Bounded + anchored on the left: the unbounded form was quadratic on long runs without "@" (40 KB ≈ 1.2 s per
# mask call, blocking the event loop for big tool outputs)
_EMAIL_RE = re.compile(
    r"(?<![A-Za-z0-9._%+-])[A-Za-z0-9._%+-]{1,64}@[A-Za-z0-9.-]{1,253}\.[A-Za-z]{2,}"
)
_PHONE_RE = re.compile(r"(?<!\d)(?<!\d[.,])(?:\(?\+?84\)?[\s.-]?|0)[35789](?:[\s.-]?\d){8}(?!\d)")
_CARD_RE = re.compile(r"(?<!\d)\d(?:[ -]?\d){14,18}(?!\d)")
_CCCD_RE = re.compile(r"(?<!\d)0(?:[0-8]\d|9[0-6])[0-3]\d{8}(?!\d)")
_ID_CONTEXT_RE = re.compile(
    r"(?i)(\b(?:cmnd|cccd|cmt|chứng minh|căn cước|định danh)\D{0,30}?|\bid\D{0,12}?)"
    r"(?<!\d)(?:\d{9}|\d{12})(?!\d)"
)
_STATUS_MESSAGE_ATTR = "langfuse.observation.status_message"
_mask_pii = True


# --------------------------------------------------------------------------- lifecycle
def init_tracing(settings: Settings) -> None:
    """Call once at startup (lifespan)."""
    global _client
    if not settings.langfuse_enabled:
        log.info("Langfuse disabled (missing LANGFUSE_PUBLIC_KEY/SECRET_KEY)")
        return
    from langfuse import Langfuse

    global _mask_pii
    _mask_pii = settings.trace_mask_pii
    extra: dict[str, Any] = {}
    if "mask_otel_spans" in inspect.signature(Langfuse).parameters:
        extra["mask_otel_spans"] = _mask_otel_spans
    else:  # older 4.x SDK: CallbackHandler error messages are only masked by _MaskingCallbackHandler
        log.warning("langfuse SDK has no mask_otel_spans — upgrade langfuse (>=4.17 verified)")
    _client = Langfuse(
        environment=settings.app_env, release=settings.agent_version, mask=_mask, **extra
    )
    log.info(
        "Langfuse tracing enabled (env=%s, release=%s)", settings.app_env, settings.agent_version
    )


def shutdown_tracing() -> None:
    if _client is not None:
        _client.flush()
        _client.shutdown()


def get_client() -> Any:
    return _client


@functools.lru_cache(
    maxsize=4096
)  # called for every dict key and every key=value candidate in text
def _is_secret_key(key: Any) -> bool:
    # camelCase → snake (accessToken → access_token, tavilyApiKey → tavily_api_key), then "-"/" " → "_"
    k = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", str(key))
    k = re.sub(r"[-\s]+", "_", k.lower())
    parts = k.split("_")
    if parts[-1] in _NOT_SECRET_LAST_PARTS:  # token_usage, credential_type, token_use… are metadata
        return False
    return any(p in _SECRET_PARTS for p in parts) or any(x in k for x in _SECRET_SUBSTRINGS)


def _key_parts(key: Any) -> list[str]:
    k = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", str(key))
    return re.sub(r"[-\s]+", "_", k.lower()).split("_")


def _is_secret_pair(key: Any, value: Any) -> bool:
    """`_is_secret_key`, plus value-aware keys: `pin` / `pin_code` only when the value is a 4–8 digit code."""
    if _is_secret_key(key):
        return True
    parts = _key_parts(key)
    if parts[-1] in _NOT_SECRET_LAST_PARTS or not any(p in _PIN_PARTS for p in parts):
        return False
    return (
        isinstance(value, int | str)
        and not isinstance(value, bool)
        and bool(_PIN_VALUE_RE.match(str(value)))
    )


def _luhn_ok(digits: str) -> bool:
    total = 0
    for i, ch in enumerate(reversed(digits)):
        d = int(ch) * (2 if i % 2 else 1)
        total += d - 9 if d > 9 else d
    return total % 10 == 0


def _mask_card(m: re.Match) -> str:
    digits = re.sub(r"\D", "", m.group(0))
    # 15–19 digits (Amex 15, Visa/MC 16…): excludes 13-digit epoch-ms timestamps that happen to pass Luhn
    return "***CARD***" if 15 <= len(digits) <= 19 and _luhn_ok(digits) else m.group(0)


def _mask_key_values(text: str) -> str:
    """`access_token=…`, `X-API-Key: …`, `"refresh_token": "…"`, `?tavilyApiKey=…&sig=…` ⇒ value → ***.

    Quoted values keep their quotes (JSON stays parseable); an auth scheme (Bearer/Basic/Token) is kept.
    Unquoted values end at whitespace or one of & , ; quotes brackets.
    """
    if "=" not in text and ":" not in text:
        return text
    out: list[str] = []
    pos = 0
    for m in _KV_KEY_RE.finditer(text):
        if m.start() < pos:
            continue
        key = m.group(2)
        if not _is_secret_key(key) and not any(p in _PIN_PARTS for p in _key_parts(key)):
            continue  # cheap pre-check: only secret / pin-like keys need their value parsed
        v = _KV_VALUE_RE.match(text, m.end())
        if v is None:
            continue
        val = v.group(0)
        if not _is_secret_pair(key, val.strip("\\\"'")):
            continue
        if val.startswith('\\"'):
            masked = '\\"***\\"'
        elif val[0] in "\"'":
            masked = f"{val[0]}***{val[0]}"
        else:
            masked = f"{v.group(1) or ''}***"
        out += [text[pos : m.end()], masked]
        pos = v.end()
    return "".join(out) + text[pos:] if out else text


def _mask_text(text: str) -> str:
    out = _URL_CRED_RE.sub(r"\1:***@", text)
    out = _BEARER_RE.sub(r"\1\2***", out)
    out = _mask_key_values(out)
    out = _API_KEY_RE.sub("***KEY***", _JWT_RE.sub("***JWT***", out))
    if _mask_pii:
        out = _EMAIL_RE.sub("***EMAIL***", out)
        out = _CARD_RE.sub(_mask_card, out)  # before phone/ID: a card contains shorter digit runs
        out = _PHONE_RE.sub("***PHONE***", out)
        out = _CCCD_RE.sub("***ID***", out)
        out = _ID_CONTEXT_RE.sub(r"\1***ID***", out)
    return out


def _mask(*, data: Any, **_: Any) -> Any:
    """Mask secrets (always) and PII (TRACE_MASK_PII) before anything leaves the process.

    Langfuse calls this with RAW Python objects and serializes them afterwards. The CallbackHandler turns
    messages into dicts and the SDK media pass model_dump()s pydantic models (unless
    LANGFUSE_MEDIA_UPLOAD_ENABLED=false), but dataclasses given to step()/event()/obs.update() would skip
    masking ⇒ convert them here exactly like the SDK serializer does (asdict / model_dump).
    """
    if isinstance(data, str):
        return _mask_text(data)
    if isinstance(data, dict):
        return {k: ("***" if _is_secret_pair(k, v) else _mask(data=v)) for k, v in data.items()}
    if isinstance(data, list | tuple | set | frozenset):
        items = list(data)
        # header pairs: [("X-API-Key", "k9…")], [["Authorization", "Bearer …"]] ⇒ ["X-API-Key", "***"]
        if (
            len(items) == 2
            and isinstance(items[0], str)
            and isinstance(items[1], str | bytes | int | float)
            and _is_secret_pair(items[0], items[1])
        ):
            return [items[0], "***"]
        return [_mask(data=v) for v in items]
    if dataclasses.is_dataclass(data) and not isinstance(data, type):
        return _mask(data=dataclasses.asdict(data))
    if isinstance(data, BaseModel):
        return _mask(data=data.model_dump())
    return data


def _mask_status(message: Any) -> str | None:
    """status_message is NOT passed through `mask` by the SDK (exception text: URLs with ?api_key=…, DSNs…)."""
    return None if message is None else _mask_text(str(message))


def _mask_otel_spans(*, params: Any) -> Any:
    """Export-stage hook (Langfuse(mask_otel_spans=…)): mask status_message on EVERY span, including the ones
    the LangChain CallbackHandler sets from LLM/tool/chain errors. Must never raise (⇒ whole batch dropped)."""
    from langfuse.types import MaskOtelSpansResult, OtelSpanPatch

    patches: dict[Any, Any] = {}
    for ident, span in params.spans.items():
        try:
            msg = span.attributes.get(_STATUS_MESSAGE_ATTR)
            if isinstance(msg, str) and (masked := _mask_text(msg)) != msg:
                patches[ident] = OtelSpanPatch(set_attributes={_STATUS_MESSAGE_ATTR: masked})
        except Exception:  # noqa: BLE001 — drop the attribute rather than the whole export batch
            log.warning("status_message masking failed", exc_info=True)
            patches[ident] = OtelSpanPatch(delete_attributes=(_STATUS_MESSAGE_ATTR,))
    return MaskOtelSpansResult(span_patches=patches)


def trace_user_id(user_id: str) -> str:
    """user_id as shown in Langfuse. Trace attributes (user_id/metadata) are NOT passed through `mask`, so an
    email-shaped id (AUTH_USER_CLAIM=email) is replaced by a stable hash when PII masking is on."""
    if _mask_pii and _EMAIL_RE.fullmatch(user_id):
        return "u-" + hashlib.sha256(user_id.encode()).hexdigest()[:16]
    return user_id


# --------------------------------------------------------------------------- LangChain bridge
@functools.cache
def _callback_handler_class() -> type:
    from langfuse.langchain import CallbackHandler

    class _MaskingCallbackHandler(CallbackHandler):
        """Masks LLM/tool/chain error text AT THE SOURCE: the SDK also copies status_message into the OTel span
        status description, which `mask_otel_spans` cannot patch (it only patches attributes)."""

        def _get_error_level_and_status_message(self, error: BaseException) -> tuple[Any, str]:
            level, message = super()._get_error_level_and_status_message(
                error
            )  # SDK-internal (4.x)
            return level, _mask_text(message)

        def on_tool_end(self, output: Any, **kwargs: Any) -> Any:
            # ToolMessage(status="error") ⇒ the SDK uses its content as status_message. Pass a masked COPY:
            # the original message object belongs to the graph state.
            if getattr(output, "status", None) == "error" and isinstance(
                getattr(output, "content", None), str
            ):
                output = output.model_copy(update={"content": _mask_text(output.content)})
            return super().on_tool_end(output, **kwargs)

    return _MaskingCallbackHandler


def langchain_callbacks() -> list[Any]:
    """CallbackHandler attached to the graph's RunnableConfig — auto-traces nodes/LLM/tools."""
    if _client is None:
        return []
    return [_callback_handler_class()()]


# --------------------------------------------------------------------------- trace / spans
@contextlib.contextmanager
def trace_request(
    *,
    settings: Settings,
    user_id: str,
    session_id: str,
    input: Any,
    metadata: dict[str, Any] | None = None,
    tags: list[str] | None = None,
) -> Iterator[Any]:
    """Root observation + propagates user/session/tags/version to ALL child observations."""
    if _client is None:
        yield None
        return
    from langfuse import propagate_attributes

    error: BaseException | None = None
    with _client.start_as_current_observation(
        name="agent.invoke", as_type="agent", input=input, metadata=metadata
    ) as root:
        with propagate_attributes(
            user_id=trace_user_id(user_id),
            session_id=session_id,
            tags=[settings.agent_name, settings.app_env, *(tags or [])],
            version=settings.agent_version,
            trace_name=f"{settings.agent_name}.invoke",
            metadata={k: str(v) for k, v in (metadata or {}).items()},
        ):
            try:
                yield root
            except BaseException as e:
                root.update(level="ERROR", status_message=_mask_status(f"{type(e).__name__}: {e}"))
                error = e
    # Re-raise OUTSIDE the span context: an exception crossing it is exported by OpenTelemetry as an
    # `exception` event + span status carrying the RAW message (neither goes through any mask).
    if error is not None:
        raise error


class _Step:
    """Span handle: always has .set(...) even when tracing is off."""

    def __init__(self, obs: Any, started: float):
        self._obs = obs
        self._started = started

    def set(
        self,
        *,
        output: Any = None,
        metadata: dict | None = None,
        level: str | None = None,
        status_message: str | None = None,
    ) -> None:
        if self._obs is None:
            return
        meta = {
            "latency_ms": round((time.perf_counter() - self._started) * 1000, 1),
            **(metadata or {}),
        }
        kwargs: dict[str, Any] = {"metadata": meta}
        if output is not None:
            kwargs["output"] = output
        if level:
            kwargs["level"] = level
        if status_message:
            kwargs["status_message"] = _mask_status(status_message)
        self._obs.update(**kwargs)


def _langchain_parent() -> Any:
    """Langfuse observation of the currently running LangChain run (node / tool), if any.

    CallbackHandler does not set the node's observation as the OTel "current span" for code inside
    the node, so custom spans must be attached manually to the current run to land correctly in the trace tree.
    """
    from langchain_core.runnables.config import var_child_runnable_config

    cfg = var_child_runnable_config.get()
    manager = cfg.get("callbacks") if cfg else None
    run_id = getattr(manager, "parent_run_id", None)
    if run_id is None:
        return None
    for h in getattr(manager, "handlers", None) or []:
        runs = getattr(h, "_runs", None)
        if runs and run_id in runs:
            return runs[run_id]
    return None


@contextlib.contextmanager
def step(
    name: str, *, input: Any = None, metadata: dict | None = None, as_type: str = "span"
) -> Iterator[_Step]:
    """Child span for NON-LangChain steps (auth, MCP, memory, compression, external APIs...).

    Attaches to the running LangGraph node/tool if any, otherwise to the current span.
    Exceptions inside are marked level=ERROR (masked status_message) and re-raised.
    """
    started = time.perf_counter()
    if _client is None:
        yield _Step(None, started)
        return
    parent = _langchain_parent()
    if parent is not None:
        obs = parent.start_observation(name=name, as_type=as_type, input=input, metadata=metadata)
        handle = _Step(obs, started)
        try:
            yield handle
        except BaseException as e:
            handle.set(level="ERROR", status_message=f"{type(e).__name__}: {e}")
            raise
        finally:
            obs.end()
        return
    error: BaseException | None = None
    with _client.start_as_current_observation(
        name=name, as_type=as_type, input=input, metadata=metadata
    ) as obs:
        handle = _Step(obs, started)
        try:
            yield handle
        except BaseException as e:
            handle.set(level="ERROR", status_message=f"{type(e).__name__}: {e}")
            error = e
    if error is not None:  # outside the span context — see trace_request
        raise error


def event(
    name: str,
    *,
    input: Any = None,
    output: Any = None,
    metadata: dict | None = None,
    level: str | None = None,
) -> None:
    """Instant marker (no duration)."""
    if _client is None:
        return
    parent = _langchain_parent()
    if parent is not None:
        parent.start_observation(
            name=name, as_type="event", input=input, output=output, metadata=metadata, level=level
        ).end()
        return
    _client.create_event(name=name, input=input, output=output, metadata=metadata, level=level)


def current_trace_id() -> str | None:
    return _client.get_current_trace_id() if _client is not None else None


def current_trace_url() -> str | None:
    return _client.get_trace_url() if _client is not None else None


def score_trace(name: str, value: float, *, comment: str | None = None) -> None:
    """Attach a score (online evaluation) to the current trace, e.g. self_eval, hitl_approved.

    Score comments are NOT passed through `mask` by the SDK ⇒ masked here."""
    trace_id = current_trace_id()
    if _client is None or trace_id is None:
        return
    _client.create_score(
        trace_id=trace_id,
        name=name,
        value=value,
        comment=_mask_status(comment),
        data_type="NUMERIC",
    )


def feedback_score_id(
    *, trace_id: str, name: str = "user_feedback", user_id: str | None = None
) -> str:
    """Deterministic score id (32 hex, same format as Langfuse.create_trace_id(seed=…)).

    Langfuse upserts a score by id ⇒ a user tapping 👍 then 👎 on the same answer keeps ONE `user_feedback`
    score holding the latest value, instead of piling up duplicates the eval loop would read as stale votes."""
    seed = f"{user_id or ''}|{trace_id}|{name}"
    return hashlib.sha256(seed.encode()).hexdigest()[:32]


def record_feedback(
    *, trace_id: str, value: float, comment: str | None = None, user_id: str | None = None
) -> bool:
    if _client is None:
        return False
    _client.create_score(
        score_id=feedback_score_id(trace_id=trace_id, user_id=user_id),
        trace_id=trace_id,
        name="user_feedback",
        value=value,
        comment=_mask_status(comment),  # free text typed by the user
        data_type="NUMERIC",
    )
    return True
